services:
  app:
    build: .
    user: ${UID}:${GID}
    environment:
      COMPOSER_CACHE_DIR: /app/runtime/cache/composer
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: php ./yii serve 0.0.0.0
